name: "Feature Request"
description: "Submit a new feature idea for OLS"
title: ""
labels: ["enhancement"]
body:
  - type: input
    id: title
    attributes:
      label: "Title"
      placeholder: "Short and descriptive feature title"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      placeholder: "Describe the feature and why it would be useful"
    validations:
      required: true
