name: "debug CI"

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          sudo apt update && sudo apt install -y lua5.1 luarocks
          python -m pip install -r requirements.txt
          sudo luarocks install luacov
      - name: Bash test
        run: |
          find src -type f -print0 | while IFS= read -r -d '' f; do
            if head -n1 "$f" | grep -qE '^#!.*(bash|sh)'; then
              echo "Testing: $f"
              bash -n "$f"
            fi
          done
      - name: Lua test
        run: |
          find src -name "*.lua" -print0 | while IFS= read -r -d '' f; do
            echo "Testing: $f"
            lua -e "assert(loadfile('$f'))"
          done
      - name: Python test
        run: pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          sudo apt update && sudo apt install -y shellcheck luarocks
          python -m pip install -r requirements.txt
          sudo luarocks install luacheck

      - name: Bash lint
        run: |
          find src -type f -print0 | while IFS= read -r -d '' f; do
            if head -n1 "$f" | grep -qE '^#!.*(bash|sh)'; then
              echo "Checking syntax: $f"
              shellcheck -x "$f"
            fi
          done
      - name: Lua lint
        run: |
          find src -name "*.lua" -print0 | while IFS= read -r -d '' f; do
            echo "Checking syntax: $f"
            luacheck "$f"
          done
      - name: Python lint
        run: |
          find src -name "*.py" -print0 | while IFS= read -r -d '' f; do
            echo "Checking syntax: $f"
            ruff check "$f"
          done
